version: '3'

services:
  laravel-app:
    build: .
    ports:
      - "3003:80"
    volumes:
      - ./:/usr/share/nginx
      - .docker/nginx:/etc/nginx/conf.d/
    networks:
      - app-network
  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldocker
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app-network
networks:
  app-network:
    driver: bridge